fix: install hadolint for hadolint command
CircleCI-Public/docker-orb pull request #175
Opened 2023-02-16 23:11 UTC by brivu

Currently if the `docker/hadolint` command is used with an `executor` other than the `hadolint` docker image, the  command fails. This `PR` installs hadolint if it isn't already.

2023-02-16 23:30 UTC, EricRibeiro requested changes

2023-02-16 23:30 UTC, EricRibeiro commented on src/scripts/hadolint.sh
> +if [ ! "$(command -v hadolint)" ]; then
You can avoid the subshell by invoking the command directly:

```suggestion
if ! command -v hadolint &> /dev/null; then
```

2023-02-17 23:25 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:a06236d8e3340e54b8c3c4fb9e95776084a35733

2023-02-17 23:45 UTC, EricRibeiro commented on src/scripts/hadolint.sh
> +    export SYS_ENV_PLATFORM="Darwin"
Are you using `SYS_ENV_PLATFORM` outside this script? If the answer is "no", I believe you don't to `export` the variable.

2023-02-17 23:45 UTC, EricRibeiro approved these changes

2023-02-18 05:34 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:c738e3152f32245b721d8aad4fa33f3c08b54386

2023-02-21 16:26 UTC, KyleTryon approved these changes

2023-02-21 20:32 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:c738e3152f32245b721d8aad4fa33f3c08b54386

2023-02-21 20:39 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:fd6f8a79381e3f7e7603519341eefe854f8a5c2d

2023-02-21 20:47 UTC, KyleTryon approved these changes

2023-02-21 20:49 UTC, merged

2023-02-21 20:49 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:b6600db35dd7b9b376f91b3e0fd27dcabc538125