fix: update dockerfile
CircleCI-Public/docker-orb pull request #176
Opened 2023-02-17 23:14 UTC by brivu

The current `Dockerfiles` (for testing purposes) uses the `ubuntu` distribution and causes the following error: 

```
Sending build context to Docker daemon  516.1kB
Step 1/5 : FROM ubuntu:20.04
manifest for ubuntu:20.04 not found
```

This `PR` changes `ubuntu` to `debian` in order to address this issue.

2023-02-17 23:43 UTC, EricRibeiro approved these changes

2023-02-21 16:16 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:d741583ab068f488f3b7547efa38a4ecf6f89179

2023-02-21 16:24 UTC, KyleTryon requested changes

2023-02-21 16:24 UTC, KyleTryon commented on test2.Dockerfile
>  # The Ubuntu-based CircleCI Docker Image. Only use Ubuntu Long-Term Support
No longer ubuntu based

2023-02-21 18:24 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:f183976e19d4d3a67338a2bb60ae2a88e2f597fe

2023-02-21 18:57 UTC, KyleTryon approved these changes

2023-02-21 20:01 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:270dc400ca1b06cd2bac0e38730a98ac4e5b2a56

2023-02-21 23:49 UTC, closed without merging